chore: usando busqueda dinamica del archivo pom

diff --git a/.github/workflows/ci-cd-backend.yml b/.github/workflows/ci-cd-backend.yml
--- a/.github/workflows/ci-cd-backend.yml
+++ b/.github/workflows/ci-cd-backend.yml
@@ -18,8 +18,18 @@ jobs:
           distribution: 'temurin'
           cache: maven
 
-      - name: Construir con Maven
-        run: mvn clean package -DskipTests
+      - name: Buscar POM y Construir con Maven
+        run: |
+          POM_PATH=$(find . -name "pom.xml" | head -n 1)
+          if [ -z "$POM_PATH" ]; then
+            echo "ERROR: ¡No se encontró ningún archivo pom.xml en ningún lado!"
+            exit 1
+          fi
+          POM_DIR=$(dirname "$POM_PATH")
+          echo "Pom encontrado en: $POM_DIR"
+          echo "POM_DIR=$POM_DIR" >> $GITHUB_ENV
+          cd "$POM_DIR"
+          mvn clean package -DskipTests
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
@@ -42,7 +52,7 @@ jobs:
       - name: Construir y subir imagen a ECR
         uses: docker/build-push-action@v5
         with:
-          context: .
+          context: ${{ env.POM_DIR }}
           push: true
           tags: ${{ steps.login-ecr.outputs.registry }}/repo-proyecto-ep2:latest
           cache-from: type=gha
